### ISSUE TITLE
[Test epic] canary test migration

### ISSUE THREAD

**Issue by Alexey-Ayupov** [AleAiu/simpletest#21]
## Canary test migration plan

We need to break down big tasks into small ones to simplify the process.

- [ ] https://github.com/AleAiu/simpletest/issues/18
- [ ] https://github.com/AleAiu/simpletest/issues/19 
- [ ] https://github.com/AleAiu/simpletest/issues/20

## Supporting documentation

n/a

## Spec Diagram

```mermaid
flowchart TD

%% <Legend>
legend --> start
subgraph legend["Legend"]
    direction LR;
    notstarted("Issue is not started"):::notstarted;
    started("Issue is in progress"):::started;
    completed("Issue is done"):::completed;
    notstarted --> started --> completed;
end

%% </Legend>


%% <CSS>

classDef notstarted fill:#FFF,color:#000;
classDef started fill:#fae17d,color:#000;
classDef completed fill:#ccffd8,color:#000;

%% </CSS>


%% <Issues>

start("Start"):::default;

canaryonactions("<a href='https://github.com/AleAiu/simpletest/issues/18' style='text-decoration:none;color: inherit;'>Develope canary tests on GH actions</a>"):::notstarted;

ghadointegration("<a href='https://github.com/AleAiu/simpletest/issues/19 ' style='text-decoration:none;color: inherit;'>Integrate canary tests into ADO pipelines</a>"):::notstarted;

testreport("<a href='https://github.com/AleAiu/simpletest/issues/20' style='text-decoration:none;color: inherit;'>Make test report readable in ADO pipelines</a>"):::notstarted;

finish("Finish"):::default;

%% </Issues>


%% <Dependencies>

start --> canaryonactions;
canaryonactions --> ghadointegration;
canaryonactions --> testreport;
ghadointegration --> finish;
testreport --> finish;

%% </Dependencies>

```
